name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  tests-and-coverage-pip:
    name: Tests and coverage (pip, Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[test]
    - name: Unit tests and coverage
      run: |
        pytest -ra --cov=. --cov-report term-missing
    - name: Upload coverage
      if: ${{ runner.os == 'Linux' && matrix.python-version == 3.7 }}
      run: |
        bash <(curl -s https://codecov.io/bash)

  tests-conda:
    name: Tests (conda, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y -c pytorch-nightly pytorch cpuonly
        conda install -y pip scipy sphinx pytest flake8
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[test]
    - name: Unit tests
      shell: bash -l {0}
      run: |
        pytest -ra
