name: Tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  tutorials:
    name: Run tutorials
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Fetch all history for all tags and branches
      # we need to do this so setuptools_scm knows how to set the botorch version
      run: git fetch --prune --unshallow
    - name: Install dependencies
      env:
        # this is so Ax's setup doesn't install a pinned BoTorch version
        ALLOW_BOTORCH_LATEST: true
      run: |
        pip install git+https://github.com/cornellius-gp/gpytorch.git
        pip install .[tutorials]
    - name: Run tutorials
      run: |
        python scripts/run_tutorials.py -p "$(pwd)" -s
